# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imgurDL.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(475, 330)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 451, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_account = QtWidgets.QWidget()
        self.tab_account.setObjectName("tab_account")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_account)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 40, 371, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_clientid = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_clientid.setObjectName("formLayout_clientid")
        self.clientIDLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.clientIDLabel.setObjectName("clientIDLabel")
        self.formLayout_clientid.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clientIDLabel)
        self.clientIDLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.clientIDLineEdit.setObjectName("clientIDLineEdit")
        self.formLayout_clientid.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.clientIDLineEdit)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_account)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 90, 371, 51))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_clientsecret = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_clientsecret.setObjectName("formLayout_clientsecret")
        self.clientSecretLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.clientSecretLabel.setObjectName("clientSecretLabel")
        self.formLayout_clientsecret.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clientSecretLabel)
        self.clientSecretLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.clientSecretLineEdit.setObjectName("clientSecretLineEdit")
        self.formLayout_clientsecret.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.clientSecretLineEdit)
        self.pushButton_submit = QtWidgets.QPushButton(self.tab_account)
        self.pushButton_submit.setGeometry(QtCore.QRect(10, 160, 421, 41))
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.label_help = QtWidgets.QLabel(self.tab_account)
        self.label_help.setGeometry(QtCore.QRect(410, 120, 16, 20))
        self.label_help.setAlignment(QtCore.Qt.AlignCenter)
        self.label_help.setObjectName("label_help")
        self.label_rightway = QtWidgets.QLabel(self.tab_account)
        self.label_rightway.setGeometry(QtCore.QRect(180, 15, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_rightway.setFont(font)
        self.label_rightway.setObjectName("label_rightway")
        self.tabWidget.addTab(self.tab_account, "")
        self.tab_download = QtWidgets.QWidget()
        self.tab_download.setObjectName("tab_download")
        self.pushButton_download = QtWidgets.QPushButton(self.tab_download)
        self.pushButton_download.setGeometry(QtCore.QRect(10, 160, 421, 41))
        self.pushButton_download.setObjectName("pushButton_download")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_download)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 40, 371, 51))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_postUrl = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_postUrl.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_postUrl.setObjectName("formLayout_postUrl")
        self.postURLLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.postURLLabel.setObjectName("postURLLabel")
        self.formLayout_postUrl.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.postURLLabel)
        self.postURLLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.postURLLineEdit.setObjectName("postURLLineEdit")
        self.formLayout_postUrl.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.postURLLineEdit)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_download)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(20, 90, 371, 51))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_downloadTo = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_downloadTo.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_downloadTo.setObjectName("formLayout_downloadTo")
        self.downloadToLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.downloadToLabel.setObjectName("downloadToLabel")
        self.formLayout_downloadTo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.downloadToLabel)
        self.downloadToLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.downloadToLineEdit.setObjectName("downloadToLineEdit")
        self.formLayout_downloadTo.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.downloadToLineEdit)
        self.pushButton_fileExplorer = QtWidgets.QPushButton(self.tab_download)
        self.pushButton_fileExplorer.setGeometry(QtCore.QRect(400, 95, 31, 24))
        self.pushButton_fileExplorer.setObjectName("pushButton_fileExplorer")
        self.label_credits = QtWidgets.QLabel(self.tab_download)
        self.label_credits.setGeometry(QtCore.QRect(60, 15, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_credits.setFont(font)
        self.label_credits.setObjectName("label_credits")
        self.tabWidget.addTab(self.tab_download, "")
        self.tab_activity = QtWidgets.QWidget()
        self.tab_activity.setObjectName("tab_activity")
        self.tableWidget_activity = QtWidgets.QTableWidget(self.tab_activity)
        self.tableWidget_activity.setGeometry(QtCore.QRect(5, 10, 431, 192))
        self.tableWidget_activity.setObjectName("tableWidget_activity")
        self.tableWidget_activity.setColumnCount(5)
        self.tableWidget_activity.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_activity.setHorizontalHeaderItem(4, item)
        self.tableWidget_activity.horizontalHeader().setDefaultSectionSize(100)
        self.tabWidget.addTab(self.tab_activity, "")
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(160, 0, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_icon = QtWidgets.QLabel(Dialog)
        self.label_icon.setGeometry(QtCore.QRect(290, 10, 20, 41))
        self.label_icon.setText("")
        self.label_icon.setObjectName("label_icon")
        self.label_title_2 = QtWidgets.QLabel(Dialog)
        self.label_title_2.setGeometry(QtCore.QRect(140, 25, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_2.setFont(font)
        self.label_title_2.setObjectName("label_title_2")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ImgurDL"))
        self.clientIDLabel.setText(_translate("Dialog", "Client ID:"))
        self.clientSecretLabel.setText(_translate("Dialog", "Client Secret:"))
        self.pushButton_submit.setText(_translate("Dialog", "Submit"))
        self.label_help.setText(_translate("Dialog", "?"))
        self.label_rightway.setText(_translate("Dialog", "The right way to do it"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_account), _translate("Dialog", "Account"))
        self.pushButton_download.setText(_translate("Dialog", "Download"))
        self.postURLLabel.setText(_translate("Dialog", "Post URL:"))
        self.downloadToLabel.setText(_translate("Dialog", "Download to:"))
        self.pushButton_fileExplorer.setText(_translate("Dialog", "..."))
        self.label_credits.setText(_translate("Dialog", "492/500 credits available and 12492/12500 resets in 00 hours, 47 minutes, 51 seconds"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_download), _translate("Dialog", "Download"))
        item = self.tableWidget_activity.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Title"))
        item = self.tableWidget_activity.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "URL"))
        item = self.tableWidget_activity.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "# Images"))
        item = self.tableWidget_activity.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Size"))
        item = self.tableWidget_activity.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_activity), _translate("Dialog", "Activity"))
        self.label_title.setText(_translate("Dialog", "Imgur DL"))
        self.label_title_2.setText(_translate("Dialog", "for posts with over 1k files"))

